name: Check PR

on: pull_request

jobs:
  deploy-preview:
    name: Preview
    uses: alphagov/govuk-accounts-explore-prototype-1/.github/workflows/deploy-to-paas.yml@d1ec049de823344b54084f6115bdffc8047c2d67
    with:
      environment: preview
      cf_space_name: sandbox
      app_name: prototype-preview-${{ github.head_ref }}
    secrets:
      cf_username: ${{ secrets.CF_USERNAME }}
      cf_password: ${{ secrets.CF_PASSWORD }}
