name: Check PR

on: pull_request

jobs:
  deploy-preview:
    name: Preview
    uses: alphagov/govuk-accounts-explore-prototype-1/.github/workflows/deploy-to-paas.yml@8c1193ea24f21a59029913ac84cd2e863e99d07e
    with:
      environment: preview
      cf_space_name: sandbox
      app_name: prototype-preview-${{ github.head_ref }}
    secrets:
      cf_username: ${{ secrets.CF_USERNAME }}
      cf_password: ${{ secrets.CF_PASSWORD }}
