name: Deploy to PaaS

on:
  workflow_call:
    inputs:
      cf_space_name: { required: true, type: string }
      app_name: { required: true, type: string }
      environment: { required: true, type: string }
      url: { required: false, type: string }
      instances: { required: false, type: number, default: 1 }
      rolling_deployment: { required: false, type: boolean, default: false }
    secrets:
      cf_username: { required: true }
      cf_password: { required: true }
    outputs:
      deployment_url:
        description: "The PaaS deployment URL"
        value: ${{ jobs.deploy.outputs.deployment_url }}

jobs:
  deploy:
    name: Deploy to PaaS
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.set_deployment_url.outputs.deployment_url }}
    outputs:
      deployment_url: ${{ steps.set_deployment_url.outputs.deployment_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Cloud Foundry client
        env:
          CF_CLI_DOWNLOAD_URL: https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github&version=v7
        run: |
          curl -sL ${CF_CLI_DOWNLOAD_URL} | sudo tar -zx -C /usr/local/bin
          cf version
      - name: Set deployment hostname
        id: set_deployment_hostname
        if: ${{ inputs.app_name != null }}
        run: |
          # Downcase the hostname and limit length to 63 characters as per PaaS requirements
          hostname=$(echo ${{ inputs.app_name }} | tr '[:upper:]' '[:lower:]' | tr '_' '-' | cut -c1-63)
          echo "::set-output name=hostname::${hostname}"
      - name: Set deployment URL
        id: set_deployment_url
        run: |
          url=${{ inputs.url }}
          hostname=${{ steps.set_deployment_hostname.outputs.hostname }}
          deployment_url=$([[ $url ]] && echo $url || echo "https://${hostname}.london.cloudapps.digital")
          echo "::set-output name=deployment_url::${deployment_url}"
      - name: PaaS login
        env:
          CF_API_URL: https://api.london.cloud.service.gov.uk
          CF_ORG_NAME: gds-digital-identity-accounts
          CF_SPACE_NAME: ${{ inputs.cf_space_name }}
          CF_USERNAME: ${{ secrets.cf_username }}
          CF_PASSWORD: ${{ secrets.cf_password }}
        run: |
          cf api ${CF_API_URL}
          cf auth
          cf target -o ${CF_ORG_NAME} -s ${CF_SPACE_NAME}
      - name: Push to PaaS
        env:
          ROLLING_DEPLOYMENT: ${{ inputs.rolling_deployment }}
          USERNAME: ${{ secrets.username }}
          PASSWORD: ${{ secrets.password }}
        run: |
          cf push ${{ steps.set_deployment_hostname.outputs.hostname }} \
            --var username=${USERNAME} \
            --var password=${PASSWORD}} \
            --var notify-api-key="" \
            --instances ${{ inputs.instances }} $([[ $ROLLING_DEPLOYMENT == "true" ]] && echo --strategy rolling)
