name: Deploy branch preview

on: pull_request

jobs:
  deploy-preview:
    name: Preview
    uses: alphagov/govuk-accounts-explore-prototype-1/.github/workflows/deploy-to-paas.yml@d2200839f64a2c630b923b66ea9f6a18e828c27e
    with:
      environment: preview
      cf_space_name: sandbox
      app_name: prototype-preview-${{ github.head_ref }}
    secrets:
      cf_username: ${{ secrets.CF_USERNAME }}
      cf_password: ${{ secrets.CF_PASSWORD }}
