name: Deploy branch preview

on: pull_request

jobs:
  deploy-preview:
    name: Preview
    uses: alphagov/govuk-accounts-explore-prototype-1/.github/workflows/deploy-to-paas.yml@b65ee373311cda1165863a4fd93a289fd66dab6d
    with:
      environment: preview
      cf_space_name: sandbox
      app_name: prototype-preview-${{ github.head_ref }}
    secrets:
      cf_username: ${{ secrets.CF_USERNAME }}
      cf_password: ${{ secrets.CF_PASSWORD }}
      username: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
      notify_api_key: ${{ secrets.NOTIFY_API_KEY }}
